### PR TITLE
Remove unused templates

### LINKED ISSUE #75: Remove unused templates

### PR DESCRIPTION
**Pull request by PBruk**
Tagging @matt-bernhardt for code-review: Resolves #75.

### CODE REVIEW

**Comment by matt-bernhardt** [comment]
This is going to be rebased on to the end of `master` (or re-created there, depending on how bad the conflict is) after #69 is resolved.

**Comment by matt-bernhardt** [comment]
@frrrances - this isn't a question that needs an answer on a Friday afternoon, but I'm trying to determine whether all of these templates are actually unneeded or not? Is this something you might be able to weigh in on, or should I try to use a tool like What The File?

**Comment by frrrances** [comment]
i think i'd prefer to redo this work when we need it or can focus on it so we can know the thinking behind any decisions about what's needed or not.

**Comment by matt-bernhardt** [comment]
I'm going to leave this open for easier finding, but this work is basically DOA after all the cleaning work and our subsequent strategy discussions. We'll have to prune unused templates still, but that work will be considered fresh.

**Comment by matt-bernhardt** [comment]
Closing this PR (but retaining branch) for whenever we pick this work up again.

**Pull request closed without merging**
